export const START_GAME = 'START_GAME';

export const NEXT_QUESTION = 'NEXT_QUESTION';
export const NEXT_QUESTION_SUCCESS = 'NEXT_QUESTION_SUCCESS';
export const NEXT_QUESTION_FAILURE = 'NEXT_QUESTION_FAILURE';

export const UPDATE_PROGRESS = 'UPDATE_PROGRESS';
export const UPDATE_PROGRESS_SUCCESS = 'UPDATE_PROGRESS_SUCCESS';
export const UPDATE_PROGRESS_FAILURE = 'UPDATE_PROGRESS_FAILURE';

export const SAVE_RESPONSE = 'SAVE_RESPONSE';
export const SAVE_RESPONSE_SUCCESS = 'SAVE_RESPONSE_SUCCESS';
export const SAVE_RESPONSE_FAILURE = 'SAVE_RESPONSE_FAILURE';

export const GET_ADDRESS = 'GET_ADDRESS';
export const GET_ADDRESS_SUCCESS = 'GET_ADDRESS_SUCCESS';
export const GET_ADDRESS_FAILURE = 'GET_ADDRESS_FAILURE';

export const SAVE_PERSON_API = 'SAVE_PERSON_API';
export const SAVE_PERSON_API_SUCCESS = 'SAVE_PERSON_API_SUCCESS';
export const SAVE_PERSON_API_FAILURE = 'SAVE_PERSON_API_FAILURE';

export const SEND_EMAIL = 'SEND_EMAIL';
export const SEND_EMAIL_SUCCESS = 'SEND_EMAIL_SUCCESS';
export const SEND_EMAIL_FAILURE = 'SEND_EMAIL_FAILURE';

export const SAVE_QUESTIONNAIRE = 'SAVE_QUESTIONNAIRE';
export const SAVE_QUESTIONNAIRE_SUCCESS = 'SAVE_QUESTIONNAIRE_SUCCESS';
export const SAVE_QUESTIONNAIRE_FAILURE = 'SAVE_QUESTIONNAIRE_FAILURE';