export const START_GAME = 'START_GAME';

export const NEXT_QUESTION = 'NEXT_QUESTION';
export const NEXT_QUESTION_SUCCESS = 'NEXT_QUESTION_SUCCESS';
export const NEXT_QUESTION_FAILURE = 'NEXT_QUESTION_FAILURE';

export const UPDATE_PROGRESS = 'UPDATE_PROGRESS';
export const UPDATE_PROGRESS_SUCCESS = 'UPDATE_PROGRESS_SUCCESS';
export const UPDATE_PROGRESS_FAILURE = 'UPDATE_PROGRESS_FAILURE';

export const SAVE_RESPONSE = 'SAVE_RESPONSE';
export const SAVE_RESPONSE_SUCCESS = 'SAVE_RESPONSE_SUCCESS';
export const SAVE_RESPONSE_FAILURE = 'SAVE_RESPONSE_FAILURE';